FROM ollama/ollama:latest

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN ollama serve & \
    until curl -s localhost:11434 > /dev/null; do \
      echo "Waiting for Ollama to start..."; \
      sleep 1; \
    done; \
    ollama pull nomic-embed-text && \
    pkill ollama